### ISSUE TITLE
Space POI Additional Info translation

### ISSUE THREAD

**Issue by DarkEviL88** [digzol/ONI-mods#1]
I would like to translate some lines from English into my language if possible.

Language - ru_RU

Total mass remaining - Остаточная масса
Maximum mass - Максимальная масса
Time until full - Время до заполнения
Refill rate - Скорость восполнения
Mass remaining - Оставшаяся масса
Extractable (resourse name) at ()°C - Добываемый () при ()°C
Available - Доступно
Unavailable - Недоступно
Recharge time - Время перезарядки

**Comment by digzol** [comment]
Thank you for your contribution! Your translations should be available on Steam in a few minutes.

**Comment by DarkEviL88** [comment]
![Безымян111ный](https://github.com/digzol/ONI-mods/assets/50534207/503b788e-8b27-4288-b4c4-ab2566dd8379)
Refill Rate fit normally, but in Russian these two words are very long (Скорость пополнения), so I'm thinking how to replace them, and I picked up the word - Восстановление. It means the same thing and the length fits.
![Безы123132123мянный](https://github.com/digzol/ONI-mods/assets/50534207/39a0f7de-bbe6-4ae2-961f-a264c1a2820b)


I also replaced the word "Добываемый" (extractable) with "Добываем.", because in Russian language words have a gender (feminine, masculine, middle) and "Добываемый" has a masculine gender, but Copper ore in Russian has a feminine gender, Sand has a masculine gender, in general, everything is complicated in Russian, so I had to shorten the ending of the word, thus giving the player as if to think up the word according to the gender of the extracted material. Since Песок (sand) is masculine, the ending of the word "Добываемый" (extractable) must also be masculine. It's even hard to explain, but I tried.

**Comment by digzol** [comment]
I thought it was pretty interesting :) Thank you
Should be updated!
